# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version of the action, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    # Rebuild daily
    - cron: '12 4 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

# Fine-grant permission
# https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-GITHUB_TOKEN
permissions:
  packages: write

env:
  ALIYUN_PREFIX: ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/llama.cpp
  DOCKERHUB_PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}/llama.cpp

jobs:
  build_and_push:
    name: Build and push Docker images
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: 'cpu'
            dockerfile: '.devops/cpu.Dockerfile'
            target: 'full'
          - tag: 'cpu'
            dockerfile: '.devops/cpu.Dockerfile'
            target: 'light'
          - tag: 'cpu'
            dockerfile: '.devops/cpu.Dockerfile'
            target: 'server'
          - tag: 'cuda13'
            dockerfile: '.devops/cuda.Dockerfile'
            target: 'full'
            cuda_version: '13.1.1'
          - tag: 'cuda13'
            dockerfile: '.devops/cuda.Dockerfile'
            target: 'light'
            cuda_version: '13.1.1'
          - tag: 'cuda13'
            dockerfile: '.devops/cuda.Dockerfile'
            target: 'server'
            cuda_version: '13.1.1'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Log in to Aliyun Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Log in to Docker Hub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Determine tag suffix
        id: suffix
        run: |
          if [[ "${{ matrix.tag }}" == "cpu" ]]; then
            echo "suffix=" >> $GITHUB_OUTPUT
          else
            echo "suffix=-${{ matrix.tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push to Aliyun Registry
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.ALIYUN_PREFIX }}:${{ matrix.target }}${{ steps.suffix.outputs.suffix }}
          file: ${{ matrix.dockerfile }}
          target: ${{ matrix.target }}
          provenance: false
          build-args: |
            ${{ matrix.cuda_version && format('CUDA_VERSION={0}', matrix.cuda_version) || '' }}
          cache-from: type=registry,ref=${{ env.ALIYUN_PREFIX }}:buildcache-${{ matrix.tag }}-amd64
          cache-to: type=inline

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKERHUB_PREFIX }}:${{ matrix.target }}${{ steps.suffix.outputs.suffix }}
          file: ${{ matrix.dockerfile }}
          target: ${{ matrix.target }}
          provenance: false
          build-args: |
            ${{ matrix.cuda_version && format('CUDA_VERSION={0}', matrix.cuda_version) || '' }}
          cache-from: type=registry,ref=${{ env.ALIYUN_PREFIX }}:buildcache-${{ matrix.tag }}-amd64
          cache-to: type=inline